# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :dev do |dev_config|
    dev_config.vm.box = "ubuntu/trusty64"
    dev_config.vm.box_version = "= 20151218.0.0"
    dev_config.vm.host_name = 'dev.local'
    dev_config.vm.network "private_network", ip: "192.168.<replace_ip>.20"
    dev_config.vm.synced_folder "vm/salt/", "/srv/salt"
    dev_config.vm.synced_folder "vm/pillar/", "/srv/pillar"

    dev_config.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 2048
    end

    dev_config.vm.provision :salt do |salt|
      salt.master_config = "vm/etc/dev_master"
      salt.master_key = "vm/keys/dev.pem"
      salt.master_pub = "vm/keys/dev.pub"
      salt.minion_config = "vm/etc/dev_minion"
      salt.minion_key = "vm/keys/dev.pem"
      salt.minion_pub = "vm/keys/dev.pub"
      salt.seed_master = {
                          "dev" => "vm/keys/dev.pub",
                         }

      salt.install_type = "stable"
      salt.install_master = true
      salt.verbose = true
      salt.colorize = true
      salt.bootstrap_options = "-P -c /tmp"
    end
  end

end
